///////////////////////////////
// Ribbon.cpp

#include <wincore.h>
#include "Ribbon.h"
#include "Application.h"

CRibbon::CRibbon() 
{ 	
}

CRibbon::~CRibbon()
{
	CoUninitialize();
}

bool CRibbon::InitializeRibbon(HWND hWnd)
{
	HRESULT hr = CoInitialize(NULL);
	if (FAILED(hr))
	{
		return false;
	} 

	// Instantiate the Ribbon framework object.
	hr = CoCreateInstance(CLSID_UIRibbonFramework, NULL, CLSCTX_INPROC_SERVER, IID_PPV_ARGS(&m_pFramework));
	if (FAILED(hr))
	{
		return false;
	}   

	// Create the IUIApplication object.
	hr = CApplication::CreateInstance((IUIApplication**)&m_pApplication);
	if (FAILED(hr))
	{
		return false;
	} 

	// Connect the host application to the Ribbon framework.
	hr = m_pFramework->Initialize(hWnd, m_pApplication);
	if (FAILED(hr))
	{
		return false;
	}

	// Load the binary markup. APPLICATION_RIBBON is the default name generated by uicc.
	hr = m_pFramework->LoadUI(GetModuleHandle(NULL), L"APPLICATION_RIBBON");
	if (FAILED(hr))
	{
		return false;
	}

	return true;
}

void CRibbon::DestroyRibbon()
{
    if (m_pFramework)
    {
        m_pFramework->Destroy();
        m_pFramework->Release();
        m_pFramework = NULL;
    }

    if (m_pApplication)
    {
        m_pApplication->Release();
        m_pApplication = NULL;
    }
}

