REM: A batch program to rebuild the .. samples using Code::Blocks.
REM: The contents of the log file is erased 


REM: Set the paths
@set PATH=c:\Program Files\CodeBlocks;%PATH%
@set PATH=c:\Program Files (x86)\CodeBlocks;%PATH%

REM: Remove old files before we start
call CleanSamples
call CleanTutorials

REM: Change the directory to the parent (Pushes the directory change on to the stack)
pushd ..\Samples
if exist "..\output\Borland" rmdir /s /q "..\output\Borland"
if exist "..\output\VS2003" rmdir /s /q "..\output\VS2003"
if exist "..\output\MinGW" rmdir /s /q "..\output\MinGW"


REM: Compile the code

codeblocks.exe --rebuild Animation\ProjectFiles\Animation.cbp               >"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Browser\ProjectFiles\Browser.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild CommonDialogs\ProjectFiles\CommonDialogs.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Console\ProjectFiles\Console.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ContextHelp\ProjectFiles\ContextHelp.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild CustomControl\ProjectFiles\CustomControl.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DateTime\ProjectFiles\DateTime.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DDXDemo\ProjectFiles\DDXDemo.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Dialog\ProjectFiles\Dialog.cbp                     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogBars\ProjectFiles\DialogBars.cbp             >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogDemo\ProjectFiles\DialogDemo.cbp             >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogResizing\ProjectFiles\DialogResizing.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogTab\ProjectFiles\DialogTab.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DLL\ProjectFiles\MakeDLL.cbp                       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DLL\ProjectFiles\TestDLL.cbp                       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Dock\ProjectFiles\Dock.cbp                         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DockContainer\ProjectFiles\DockContainer.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DockTabbedMDI\ProjectFiles\DockTabbedMDI.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DoubleBuffer\ProjectFiles\DoubleBuffer.cbp         >>"..\output\CodeBlocks.log"
REM codeblocks.exe --rebuild DX\ProjectFiles\DX.cbp                         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Explorer\ProjectFiles\Explorer.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FastGDI\ProjectFiles\FastGDI.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FilePrintPreview\ProjectFiles\FilePrintPreview.cbp >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FormDocView\ProjectFiles\FormDemo.cbp              >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Frame\ProjectFiles\Frame.cbp                       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild GDIPlus\ProjectFiles\GDIPlus.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild INIFrame\ProjectFiles\INIFrame.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ListView\ProjectFiles\ListView.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIDockFrame\ProjectFiles\MDIDockFrame.cbp         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIFrame\ProjectFiles\MDIFrame.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIFrameDemo\ProjectFiles\MDIDemo.cbp              >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIFrameSplitter\ProjectFiles\MDIFrameSplitter.cbp >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MetaFile\ProjectFiles\MetaFile.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NetClient\ProjectFiles\NetClient.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NetClientAsync\ProjectFiles\NetClientAsync.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NetServer\ProjectFiles\NetServer.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NetServerAsync\ProjectFiles\NetServerAsync.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NotePad\ProjectFiles\Notepad.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Performance\ProjectFiles\Performance.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Picture\ProjectFiles\Picture.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild PrintDialogEx\ProjectFiles\PrintDialogEx.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild PrintPreview\ProjectFiles\PrintPreview.cbp         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild PropertySheet\ProjectFiles\PropertySheet.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ReBarDemo\ProjectFiles\ReBarDemo.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild RoundWindow\ProjectFiles\Round.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Scribble\ProjectFiles\Scribble.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Simple\ProjectFiles\Simple.cbp                     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Splitter\ProjectFiles\Splitter.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild StatusBar\ProjectFiles\StatusBar.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TabDemo\ProjectFiles\TabDemo.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TaskDialog\ProjectFiles\TaskDialog.cbp             >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TextFileReader\ProjectFiles\TextFileReader.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Themes\ProjectFiles\Themes.cbp                     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Threads\ProjectFiles\Threads.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TimeDemo\ProjectFiles\TimeDemo.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ToolBarDemo\ProjectFiles\ToolBarDemo.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ToolTips\ProjectFiles\ToolTips.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tray\ProjectFiles\Tray.cbp                         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild WinPlot\ProjectFiles\WinPlot.cbp                   >>"..\output\CodeBlocks.log"

REM: Copy the executables to the testing directories
mkdir "..\output\VS2003"
mkdir "..\output\VS2003\Debug"

ECHO "Copying VS2003 Debug files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\Microsoft\Debug\Animation.exe               "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\Microsoft\Debug\Browser.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy CommonDialogs\ProjectFiles\Microsoft\Debug\CommonDialogs.exe       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\Microsoft\Debug\Console.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy ContextHelp\ProjectFiles\Microsoft\Debug\ContextHelp.exe           "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\Microsoft\Debug\CustomControl.exe       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\Microsoft\Debug\DateTime.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\Microsoft\Debug\DDXDemo.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\Microsoft\Debug\Dialog.exe                     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\Microsoft\Debug\DialogBars.exe             "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\Microsoft\Debug\DialogDemo.exe             "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\Microsoft\Debug\DialogResizing.exe     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\Microsoft\Debug\DialogTab.exe               "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Microsoft\Debug\MyDLL.dll                         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Microsoft\Debug\TestDLL.exe                       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\Microsoft\Debug\Dock.exe                         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\Microsoft\Debug\DockContainer.exe       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\Microsoft\Debug\DockTabbedMDI.exe       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\Microsoft\Debug\DoubleBuffer.exe         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\Microsoft\Debug\FilePrintPreview.exe "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\Microsoft\Debug\FormDemo.exe              "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
REM copy DX\ProjectFiles\Microsoft\Debug\DX.exe                         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\Microsoft\Debug\Explorer.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\Microsoft\Debug\FastGDI.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\Microsoft\Debug\Frame.exe                       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy GDIPlus\ProjectFiles\Microsoft\Debug\GDIPlus.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\Microsoft\Debug\INIFrame.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\Microsoft\Debug\ListView.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\Microsoft\Debug\MDIDockFrame.exe         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\Microsoft\Debug\MDIFrame.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\Microsoft\Debug\MDIDemo.exe              "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\Microsoft\Debug\MDIFrameSplitter.exe "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\Microsoft\Debug\MetaFile.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\Microsoft\Debug\NetClient.exe               "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy NetClientAsync\ProjectFiles\Microsoft\Debug\NetClientAsync.exe     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\Microsoft\Debug\NetServer.exe               "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy NetServerAsync\ProjectFiles\Microsoft\Debug\NetServerAsync.exe     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\Microsoft\Debug\Notepad.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\Microsoft\Debug\Performance.exe           "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\Microsoft\Debug\Picture.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy PrintPreview\ProjectFiles\Microsoft\Debug\PrintPreview.exe         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\Microsoft\Debug\PropertySheet.exe       "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\Microsoft\Debug\ReBarDemo.exe               "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\Microsoft\Debug\Round.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\Microsoft\Debug\Scribble.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\Microsoft\Debug\Simple.exe                     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\Microsoft\Debug\Splitter.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\Microsoft\Debug\StatusBar.exe               "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\Microsoft\Debug\TabDemo.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\Microsoft\Debug\TextFileReader.exe     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\Microsoft\Debug\Themes.exe                     "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\Microsoft\Debug\Threads.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\Microsoft\Debug\TimeDemo.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\Microsoft\Debug\ToolBarDemo.exe           "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\Microsoft\Debug\ToolTips.exe                 "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\Microsoft\Debug\Tray.exe                         "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"
copy WinPlot\ProjectFiles\Microsoft\Debug\WinPlot.exe                   "..\output\VS2003\Debug"    >>"..\output\CodeBlocks.log"

mkdir "..\output\VS2003\Release"

ECHO "Copying VS2003 Release files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\Microsoft\Release\Animation.exe               "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\Microsoft\Release\Browser.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy CommonDialogs\ProjectFiles\Microsoft\Release\CommonDialogs.exe       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\Microsoft\Release\Console.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy ContextHelp\ProjectFiles\Microsoft\Release\ContextHelp.exe           "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\Microsoft\Release\CustomControl.exe       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\Microsoft\Release\DateTime.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\Microsoft\Release\DDXDemo.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\Microsoft\Release\Dialog.exe                     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\Microsoft\Release\DialogBars.exe             "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\Microsoft\Release\DialogDemo.exe             "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\Microsoft\Release\DialogResizing.exe     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\Microsoft\Release\DialogTab.exe               "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Microsoft\Release\MyDLL.dll                         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Microsoft\Release\TestDLL.exe                       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\Microsoft\Release\Dock.exe                         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\Microsoft\Release\DockContainer.exe       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\Microsoft\Release\DockTabbedMDI.exe       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\Microsoft\Release\DoubleBuffer.exe         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
REM copy DX\ProjectFiles\Microsoft\Release\DX.exe                         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\Microsoft\Release\Explorer.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\Microsoft\Release\FastGDI.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\Microsoft\Release\FilePrintPreview.exe "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\Microsoft\Release\FormDemo.exe              "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\Microsoft\Release\Frame.exe                       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy GDIPlus\ProjectFiles\Microsoft\Release\GDIPlus.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\Microsoft\Release\INIFrame.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\Microsoft\Release\ListView.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\Microsoft\Release\MDIDockFrame.exe         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\Microsoft\Release\MDIFrame.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\Microsoft\Release\MDIDemo.exe              "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\Microsoft\Release\MDIFrameSplitter.exe "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\Microsoft\Release\MetaFile.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\Microsoft\Release\NetClient.exe               "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy NetClientAsync\ProjectFiles\Microsoft\Release\NetClientAsync.exe     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\Microsoft\Release\NetServer.exe               "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy NetServerAsync\ProjectFiles\Microsoft\Release\NetServerAsync.exe     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\Microsoft\Release\Notepad.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\Microsoft\Release\Performance.exe           "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\Microsoft\Release\Picture.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy PrintPreview\ProjectFiles\Microsoft\Release\PrintPreview.exe         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\Microsoft\Release\PropertySheet.exe       "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\Microsoft\Release\ReBarDemo.exe               "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\Microsoft\Release\Round.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\Microsoft\Release\Scribble.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\Microsoft\Release\Simple.exe                     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\Microsoft\Release\Splitter.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\Microsoft\Release\StatusBar.exe               "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\Microsoft\Release\TabDemo.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\Microsoft\Release\TextFileReader.exe     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\Microsoft\Release\Themes.exe                     "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\Microsoft\Release\Threads.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\Microsoft\Release\TimeDemo.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\Microsoft\Release\ToolBarDemo.exe           "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\Microsoft\Release\ToolTips.exe                 "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\Microsoft\Release\Tray.exe                         "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"
copy WinPlot\ProjectFiles\Microsoft\Release\WinPlot.exe                   "..\output\VS2003\Release"    >>"..\output\CodeBlocks.log"


REM: Copy the executables to the testing directories
mkdir "..\output\Borland"
mkdir "..\output\Borland\Debug"

ECHO "Copying Borland Debug files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\Borland\Debug\Animation.exe               "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\Borland\Debug\Browser.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
REM copy CommonDialogs\ProjectFiles\Borland\Debug\CommonDialogs.exe       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\Borland\Debug\Console.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy ContextHelp\ProjectFiles\Borland\Debug\ContextHelp.exe           "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\Borland\Debug\CustomControl.exe       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\Borland\Debug\DateTime.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\Borland\Debug\DDXDemo.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\Borland\Debug\Dialog.exe                     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\Borland\Debug\DialogBars.exe             "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\Borland\Debug\DialogDemo.exe             "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\Borland\Debug\DialogResizing.exe     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\Borland\Debug\DialogTab.exe               "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Borland\Debug\MyDLL.dll                         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Borland\Debug\TestDLL.exe                       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\Borland\Debug\Dock.exe                         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\Borland\Debug\DockContainer.exe       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\Borland\Debug\DockTabbedMDI.exe       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\Borland\Debug\DoubleBuffer.exe         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
REM copy DX\ProjectFiles\Borland\Debug\DX.exe                         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\Borland\Debug\Explorer.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\Borland\Debug\FastGDI.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\Borland\Debug\FilePrintPreview.exe "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\Borland\Debug\FormDemo.exe              "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\Borland\Debug\Frame.exe                       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\Borland\Debug\INIFrame.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\Borland\Debug\ListView.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\Borland\Debug\MDIDockFrame.exe         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\Borland\Debug\MDIFrame.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\Borland\Debug\MDIDemo.exe              "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\Borland\Debug\MDIFrameSplitter.exe "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\Borland\Debug\MetaFile.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\Borland\Debug\NetClient.exe               "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy NetClientAsync\ProjectFiles\Borland\Debug\NetClientAsync.exe     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\Borland\Debug\NetServer.exe               "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy NetServerAsync\ProjectFiles\Borland\Debug\NetServerAsync.exe     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\Borland\Debug\Notepad.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\Borland\Debug\Performance.exe           "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\Borland\Debug\Picture.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy PrintPreview\ProjectFiles\Borland\Debug\PrintPreview.exe         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\Borland\Debug\PropertySheet.exe       "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\Borland\Debug\ReBarDemo.exe               "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\Borland\Debug\Round.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\Borland\Debug\Scribble.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\Borland\Debug\Simple.exe                     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\Borland\Debug\Splitter.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\Borland\Debug\StatusBar.exe               "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\Borland\Debug\TabDemo.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\Borland\Debug\TextFileReader.exe     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\Borland\Debug\Themes.exe                     "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\Borland\Debug\Threads.exe                   "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\Borland\Debug\TimeDemo.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\Borland\Debug\ToolBarDemo.exe           "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\Borland\Debug\ToolTips.exe                 "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\Borland\Debug\Tray.exe                         "..\output\Borland\Debug"    >>"..\output\CodeBlocks.log"

mkdir "..\output\Borland\Release"

ECHO "Copying Borland Release files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\Borland\Release\Animation.exe               "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\Borland\Release\Browser.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
REM copy CommonDialogs\ProjectFiles\Borland\Release\CommonDialogs.exe       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\Borland\Release\Console.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy ContextHelp\ProjectFiles\Borland\Release\ContextHelp.exe           "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\Borland\Release\CustomControl.exe       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\Borland\Release\DateTime.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\Borland\Release\DDXDemo.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\Borland\Release\Dialog.exe                     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\Borland\Release\DialogBars.exe             "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\Borland\Release\DialogDemo.exe             "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\Borland\Release\DialogResizing.exe     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\Borland\Release\DialogTab.exe               "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Borland\Release\MyDLL.dll                         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\Borland\Release\TestDLL.exe                       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\Borland\Release\Dock.exe                         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\Borland\Release\DockContainer.exe       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\Borland\Release\DockTabbedMDI.exe       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\Borland\Release\DoubleBuffer.exe         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
REM copy DX\ProjectFiles\Borland\Release\DX.exe                         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\Borland\Release\Explorer.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\Borland\Release\FastGDI.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\Borland\Release\FilePrintPreview.exe "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\Borland\Release\FormDemo.exe              "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\Borland\Release\Frame.exe                       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\Borland\Release\INIFrame.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\Borland\Release\ListView.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\Borland\Release\MDIDockFrame.exe         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\Borland\Release\MDIFrame.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\Borland\Release\MDIDemo.exe              "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\Borland\Release\MDIFrameSplitter.exe "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\Borland\Release\MetaFile.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\Borland\Release\NetClient.exe               "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy NetClientAsync\ProjectFiles\Borland\Release\NetClientAsync.exe     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\Borland\Release\NetServer.exe               "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy NetServerAsync\ProjectFiles\Borland\Release\NetServerAsync.exe     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\Borland\Release\Notepad.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\Borland\Release\Performance.exe           "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\Borland\Release\Picture.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy PrintPreview\ProjectFiles\Borland\Release\PrintPreview.exe         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\Borland\Release\PropertySheet.exe       "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\Borland\Release\ReBarDemo.exe               "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\Borland\Release\Round.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\Borland\Release\Scribble.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\Borland\Release\Simple.exe                     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\Borland\Release\Splitter.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\Borland\Release\StatusBar.exe               "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\Borland\Release\TabDemo.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\Borland\Release\TextFileReader.exe     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\Borland\Release\Themes.exe                     "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\Borland\Release\Threads.exe                   "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\Borland\Release\TimeDemo.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\Borland\Release\ToolBarDemo.exe           "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\Borland\Release\ToolTips.exe                 "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\Borland\Release\Tray.exe                         "..\output\Borland\Release"    >>"..\output\CodeBlocks.log"


REM: Copy the executables to the testing directories
mkdir "..\output\MinGW"
mkdir "..\output\MinGW\Debug"

ECHO "Copying MinGW Debug files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\GNU\Debug\Animation.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\GNU\Debug\Browser.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy CommonDialogs\ProjectFiles\GNU\Debug\CommonDialogs.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\GNU\Debug\Console.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
REM copy ContextHelp\ProjectFiles\GNU\Debug\ContextHelp.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\GNU\Debug\CustomControl.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\GNU\Debug\DateTime.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\GNU\Debug\DDXDemo.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\GNU\Debug\Dialog.exe                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\GNU\Debug\DialogBars.exe             "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\GNU\Debug\DialogDemo.exe             "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\GNU\Debug\DialogResizing.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\GNU\Debug\DialogTab.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\GNU\Debug\MyDLL.dll                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\GNU\Debug\TestDLL.exe                       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\GNU\Debug\Dock.exe                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\GNU\Debug\DockContainer.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\GNU\Debug\DockTabbedMDI.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\GNU\Debug\DoubleBuffer.exe         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
REM copy DX\ProjectFiles\GNU\Debug\DX.exe                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\GNU\Debug\Explorer.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\GNU\Debug\FastGDI.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\GNU\Debug\FilePrintPreview.exe "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\GNU\Debug\FormDemo.exe              "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\GNU\Debug\Frame.exe                       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy GDIPlus\ProjectFiles\GNU\Debug\GDIPlus.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\GNU\Debug\INIFrame.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\GNU\Debug\ListView.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\GNU\Debug\MDIDockFrame.exe         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\GNU\Debug\MDIFrame.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\GNU\Debug\MDIDemo.exe              "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\GNU\Debug\MDIFrameSplitter.exe "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\GNU\Debug\MetaFile.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\GNU\Debug\NetClient.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NetClientAsync\ProjectFiles\GNU\Debug\NetClientAsync.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\GNU\Debug\NetServer.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NetServerAsync\ProjectFiles\GNU\Debug\NetServerAsync.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\GNU\Debug\Notepad.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\GNU\Debug\Performance.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\GNU\Debug\Picture.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy PrintDialogEx\ProjectFiles\GNU\Debug\PrintDialogEx.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy PrintPreview\ProjectFiles\GNU\Debug\PrintPreview.exe         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\GNU\Debug\PropertySheet.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\GNU\Debug\ReBarDemo.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\GNU\Debug\Round.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\GNU\Debug\Scribble.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\GNU\Debug\Simple.exe                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\GNU\Debug\Splitter.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\GNU\Debug\StatusBar.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\GNU\Debug\TabDemo.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TaskDialog\ProjectFiles\GNU\Debug\TaskDialog.exe             "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\GNU\Debug\TextFileReader.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\GNU\Debug\Themes.exe                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\GNU\Debug\Threads.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\GNU\Debug\TimeDemo.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\GNU\Debug\ToolBarDemo.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\GNU\Debug\ToolTips.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\GNU\Debug\Tray.exe                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy WinPlot\ProjectFiles\GNU\Debug\WinPlot.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"

mkdir "..\output\MinGW\Release"

ECHO "Copying MinGW Release files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\GNU\Release\Animation.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\GNU\Release\Browser.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy CommonDialogs\ProjectFiles\GNU\Release\CommonDialogs.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\GNU\Release\Console.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
REM copy ContextHelp\ProjectFiles\GNU\Release\ContextHelp.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\GNU\Release\CustomControl.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\GNU\Release\DateTime.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\GNU\Release\DDXDemo.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\GNU\Release\Dialog.exe                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\GNU\Release\DialogBars.exe             "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\GNU\Release\DialogDemo.exe             "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\GNU\Release\DialogResizing.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\GNU\Release\DialogTab.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\GNU\Release\MyDLL.dll                         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DLL\ProjectFiles\GNU\Release\TestDLL.exe                       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\GNU\Release\Dock.exe                         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\GNU\Release\DockContainer.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\GNU\Release\DockTabbedMDI.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\GNU\Release\DoubleBuffer.exe         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
REM copy DX\ProjectFiles\GNU\Release\DX.exe                         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\GNU\Release\Explorer.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\GNU\Release\FastGDI.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\GNU\Release\FilePrintPreview.exe "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\GNU\Release\FormDemo.exe              "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\GNU\Release\Frame.exe                       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy GDIPlus\ProjectFiles\GNU\Release\GDIPlus.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\GNU\Release\INIFrame.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\GNU\Release\ListView.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\GNU\Release\MDIDockFrame.exe         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\GNU\Release\MDIFrame.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\GNU\Release\MDIDemo.exe              "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\GNU\Release\MDIFrameSplitter.exe "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\GNU\Release\MetaFile.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\GNU\Release\NetClient.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NetClientAsync\ProjectFiles\GNU\Release\NetClientAsync.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\GNU\Release\NetServer.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NetServerAsync\ProjectFiles\GNU\Release\NetServerAsync.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\GNU\Release\Notepad.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\GNU\Release\Performance.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\GNU\Release\Picture.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy PrintDialogEx\ProjectFiles\GNU\Release\PrintDialogEx.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy PrintPreview\ProjectFiles\GNU\Release\PrintPreview.exe         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\GNU\Release\PropertySheet.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\GNU\Release\ReBarDemo.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\GNU\Release\Round.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\GNU\Release\Scribble.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\GNU\Release\Simple.exe                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\GNU\Release\Splitter.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\GNU\Release\StatusBar.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\GNU\Release\TabDemo.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TaskDialog\ProjectFiles\GNU\Release\TaskDialog.exe             "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\GNU\Release\TextFileReader.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\GNU\Release\Themes.exe                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\GNU\Release\Threads.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\GNU\Release\TimeDemo.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\GNU\Release\ToolBarDemo.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\GNU\Release\ToolTips.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\GNU\\Release\Tray.exe                        "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy WinPlot\ProjectFiles\GNU\\Release\WinPlot.exe                  "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"


REM: Pop the directory change off the stack
popd

