REM: A batch program to rebuild the .. samples using Code::Blocks.
REM: The contents of the log file is erased 


REM: Set the paths
@set PATH=c:\Program Files\CodeBlocks;%PATH%
@set PATH=c:\Program Files (x86)\CodeBlocks;%PATH%

REM: Remove old files before we start
call CleanSamples
call CleanTutorials

REM: Change the directory to the parent (Pushes the directory change on to the stack)
pushd ..\Samples
if exist "..\output\MinGW" rmdir /s /q "..\output\MinGW"


REM: Compile the code

codeblocks.exe --rebuild Animation\ProjectFiles\Animation.cbp               >"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Browser\ProjectFiles\Browser.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild CommonDialogs\ProjectFiles\CommonDialogs.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Console\ProjectFiles\Console.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ContextHelp\ProjectFiles\ContextHelp.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild CustomControl\ProjectFiles\CustomControl.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild CustomPrintDlg\ProjectFiles\CustomPrintDlg.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DateTime\ProjectFiles\DateTime.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DDXDemo\ProjectFiles\DDXDemo.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Dialog\ProjectFiles\Dialog.cbp                     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogBars\ProjectFiles\DialogBars.cbp             >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogDemo\ProjectFiles\DialogDemo.cbp             >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogResizing\ProjectFiles\DialogResizing.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogTab\ProjectFiles\DialogTab.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DialogTemplate\ProjectFiles\DialogTemplate.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Dock\ProjectFiles\Dock.cbp                         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DockContainer\ProjectFiles\DockContainer.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DockTabbedMDI\ProjectFiles\DockTabbedMDI.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild DoubleBuffer\ProjectFiles\DoubleBuffer.cbp         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Explorer\ProjectFiles\Explorer.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FastGDI\ProjectFiles\FastGDI.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FilePrintPreview\ProjectFiles\FilePrintPreview.cbp >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FormDocView\ProjectFiles\FormDemo.cbp              >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Frame\ProjectFiles\Frame.cbp                       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild FrameEx\ProjectFiles\FrameEx.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild GDIPlus\ProjectFiles\GDIPlus.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild IFileDialog\ProjectFiles\IFileDialog.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild INIFrame\ProjectFiles\INIFrame.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ListView\ProjectFiles\ListView.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MakeDLL\ProjectFiles\MakeDLL.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIDockFrame\ProjectFiles\MDIDockFrame.cbp         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIFrame\ProjectFiles\MDIFrame.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIFrameDemo\ProjectFiles\MDIFrameDemo.cbp         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MDIFrameSplitter\ProjectFiles\MDIFrameSplitter.cbp >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MetaFile\ProjectFiles\MetaFile.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild MovieShow\ProjectFiles\MovieShow.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NetClient\ProjectFiles\NetClient.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NetServer\ProjectFiles\NetServer.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild NotePad\ProjectFiles\Notepad.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Performance\ProjectFiles\Performance.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Picture\ProjectFiles\Picture.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild PropertySheet\ProjectFiles\PropertySheet.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ReBarDemo\ProjectFiles\ReBarDemo.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild RoundWindow\ProjectFiles\RoundWindow.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ScintillaDemo\ProjectFiles\ScintillaDemo.cbp       >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Scribble\ProjectFiles\Scribble.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Simple\ProjectFiles\Simple.cbp                     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Splitter\ProjectFiles\Splitter.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild StatusBar\ProjectFiles\StatusBar.cbp               >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TabDemo\ProjectFiles\TabDemo.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TaskDialog\ProjectFiles\TaskDialog.cbp             >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TestDLL\ProjectFiles\TestDLL.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TextFileReader\ProjectFiles\TextFileReader.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Themes\ProjectFiles\Themes.cbp                     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Threads\ProjectFiles\Threads.cbp                   >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild TimeDemo\ProjectFiles\TimeDemo.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ToolBarBuilder\ProjectFiles\ToolBarBuilder.cbp     >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ToolBarDemo\ProjectFiles\ToolBarDemo.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild ToolTips\ProjectFiles\ToolTips.cbp                 >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tray\ProjectFiles\Tray.cbp                         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild WinPlot\ProjectFiles\WinPlot.cbp                   >>"..\output\CodeBlocks.log"

REM: Copy the executables to the testing directories
mkdir "..\output\MinGW"
mkdir "..\output\MinGW\Debug"

ECHO "Copying MinGW Debug files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\GNU\Debug\Animation.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\GNU\Debug\Browser.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy CommonDialogs\ProjectFiles\GNU\Debug\CommonDialogs.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\GNU\Debug\Console.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ContextHelp\ProjectFiles\GNU\Debug\ContextHelp.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ContextHelp\Setup\ContextHelp.chm                            "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\GNU\Debug\CustomControl.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy CustomPrintDlg\ProjectFiles\GNU\Debug\CustomPrintDlg.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\GNU\Debug\DateTime.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\GNU\Debug\DDXDemo.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\GNU\Debug\Dialog.exe                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\GNU\Debug\DialogBars.exe             "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\GNU\Debug\DialogDemo.exe             "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\GNU\Debug\DialogResizing.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\GNU\Debug\DialogTab.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DialogTemplate\ProjectFiles\GNU\Debug\DialogTemplate.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\GNU\Debug\Dock.exe                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\GNU\Debug\DockContainer.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\GNU\Debug\DockTabbedMDI.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\GNU\Debug\DoubleBuffer.exe         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\GNU\Debug\Explorer.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\GNU\Debug\FastGDI.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\GNU\Debug\FilePrintPreview.exe "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\GNU\Debug\FormDemo.exe              "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\GNU\Debug\Frame.exe                       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy FrameEx\ProjectFiles\GNU\Debug\FrameEx.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy GDIPlus\ProjectFiles\GNU\Debug\GDIPlus.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy IFileDialog\ProjectFiles\GNU\Debug\IFileDialog.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\GNU\Debug\INIFrame.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\GNU\Debug\ListView.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MakeDLL\ProjectFiles\GNU\Debug\MyDLL.dll                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\GNU\Debug\MDIDockFrame.exe         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\GNU\Debug\MDIFrame.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\GNU\Debug\MDIFrameDemo.exe         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\GNU\Debug\MDIFrameSplitter.exe "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\GNU\Debug\MetaFile.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy MovieShow\ProjectFiles\GNU\Debug\MovieShow.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\GNU\Debug\NetClient.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\GNU\Debug\NetServer.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\GNU\Debug\Notepad.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\GNU\Debug\Performance.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\GNU\Debug\Picture.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\GNU\Debug\PropertySheet.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\GNU\Debug\ReBarDemo.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\GNU\Debug\RoundWindow.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ScintillaDemo\ProjectFiles\GNU\Debug\ScintillaDemo.exe       "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ScintillaDemo\DLLs\x64\Scintilla.dll                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\GNU\Debug\Scribble.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\GNU\Debug\Simple.exe                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\GNU\Debug\Splitter.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\GNU\Debug\StatusBar.exe               "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\GNU\Debug\TabDemo.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TaskDialog\ProjectFiles\GNU\Debug\TaskDialog.exe             "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TestDLL\ProjectFiles\GNU\Debug\TestDLL.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\GNU\Debug\TextFileReader.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\GNU\Debug\Themes.exe                     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\GNU\Debug\Threads.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\GNU\Debug\TimeDemo.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ToolBarBuilder\ProjectFiles\GNU\Debug\ToolBarBuilder.exe     "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\GNU\Debug\ToolBarDemo.exe           "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\GNU\Debug\ToolTips.exe                 "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\GNU\Debug\Tray.exe                         "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"
copy WinPlot\ProjectFiles\GNU\Debug\WinPlot.exe                   "..\output\MinGW\Debug"    >>"..\output\CodeBlocks.log"

mkdir "..\output\MinGW\Release"

ECHO "Copying MinGW Release files" >>"..\output\CodeBlocks.log"
copy Animation\ProjectFiles\GNU\Release\Animation.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Browser\ProjectFiles\GNU\Release\Browser.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy CommonDialogs\ProjectFiles\GNU\Release\CommonDialogs.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Console\ProjectFiles\GNU\Release\Console.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ContextHelp\ProjectFiles\GNU\Release\ContextHelp.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ContextHelp\Setup\ContextHelp.chm                              "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy CustomControl\ProjectFiles\GNU\Release\CustomControl.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy CustomPrintDlg\ProjectFiles\GNU\Release\CustomPrintDlg.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DateTime\ProjectFiles\GNU\Release\DateTime.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DDXDemo\ProjectFiles\GNU\Release\DDXDemo.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Dialog\ProjectFiles\GNU\Release\Dialog.exe                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogBars\ProjectFiles\GNU\Release\DialogBars.exe             "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogDemo\ProjectFiles\GNU\Release\DialogDemo.exe             "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogResizing\ProjectFiles\GNU\Release\DialogResizing.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogTab\ProjectFiles\GNU\Release\DialogTab.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DialogTemplate\ProjectFiles\GNU\Release\DialogTemplate.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Dock\ProjectFiles\GNU\Release\Dock.exe                         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DockContainer\ProjectFiles\GNU\Release\DockContainer.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DockTabbedMDI\ProjectFiles\GNU\Release\DockTabbedMDI.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy DoubleBuffer\ProjectFiles\GNU\Release\DoubleBuffer.exe         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Explorer\ProjectFiles\GNU\Release\Explorer.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FastGDI\ProjectFiles\GNU\Release\FastGDI.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FilePrintPreview\ProjectFiles\GNU\Release\FilePrintPreview.exe "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FormDocView\ProjectFiles\GNU\Release\FormDemo.exe              "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Frame\ProjectFiles\GNU\Release\Frame.exe                       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy FrameEx\ProjectFiles\GNU\Release\FrameEx.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy GDIPlus\ProjectFiles\GNU\Release\GDIPlus.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy IFileDialog\ProjectFiles\GNU\Release\IFileDialog.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy INIFrame\ProjectFiles\GNU\Release\INIFrame.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ListView\ProjectFiles\GNU\Release\ListView.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MakeDLL\ProjectFiles\GNU\Release\MyDLL.dll                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIDockFrame\ProjectFiles\GNU\Release\MDIDockFrame.exe         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrame\ProjectFiles\GNU\Release\MDIFrame.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameDemo\ProjectFiles\GNU\Release\MDIFrameDemo.exe         "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MDIFrameSplitter\ProjectFiles\GNU\Release\MDIFrameSplitter.exe "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MetaFile\ProjectFiles\GNU\Release\MetaFile.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy MovieShow\ProjectFiles\GNU\Release\MovieShow.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NetClient\ProjectFiles\GNU\Release\NetClient.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NetServer\ProjectFiles\GNU\Release\NetServer.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy NotePad\ProjectFiles\GNU\Release\Notepad.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Performance\ProjectFiles\GNU\Release\Performance.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Picture\ProjectFiles\GNU\Release\Picture.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy PropertySheet\ProjectFiles\GNU\Release\PropertySheet.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ReBarDemo\ProjectFiles\GNU\Release\ReBarDemo.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy RoundWindow\ProjectFiles\GNU\Release\RoundWindow.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ScintillaDemo\ProjectFiles\GNU\Release\ScintillaDemo.exe       "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ScintillaDemo\DLLs\x64\Scintilla.dll                           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Scribble\ProjectFiles\GNU\Release\Scribble.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Simple\ProjectFiles\GNU\Release\Simple.exe                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Splitter\ProjectFiles\GNU\Release\Splitter.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy StatusBar\ProjectFiles\GNU\Release\StatusBar.exe               "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TabDemo\ProjectFiles\GNU\Release\TabDemo.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TaskDialog\ProjectFiles\GNU\Release\TaskDialog.exe             "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TestDLL\ProjectFiles\GNU\Release\TestDLL.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TextFileReader\ProjectFiles\GNU\Release\TextFileReader.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Themes\ProjectFiles\GNU\Release\Themes.exe                     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Threads\ProjectFiles\GNU\Release\Threads.exe                   "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy TimeDemo\ProjectFiles\GNU\Release\TimeDemo.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ToolBarBuilder\ProjectFiles\GNU\Release\ToolBarBuilder.exe     "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ToolBarDemo\ProjectFiles\GNU\Release\ToolBarDemo.exe           "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy ToolTips\ProjectFiles\GNU\Release\ToolTips.exe                 "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy Tray\ProjectFiles\GNU\\Release\Tray.exe                        "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"
copy WinPlot\ProjectFiles\GNU\\Release\WinPlot.exe                  "..\output\MinGW\Release"    >>"..\output\CodeBlocks.log"


REM: Change the directory to the Tutorials parent
popd
pushd ..\Tutorials

REM: Compile Tutorials
ECHO "Compiling Tutorials" >>"..\output\CodeBlocks.log"
::Compile code
codeblocks.exe --rebuild Tutorial1\ProjectFiles\Tutorial1.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial2\ProjectFiles\Tutorial2.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial3\ProjectFiles\Tutorial3.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial4\ProjectFiles\Tutorial4.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial5\ProjectFiles\Tutorial5.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial6\ProjectFiles\Tutorial6.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial7\ProjectFiles\Tutorial7.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial8\ProjectFiles\Tutorial8.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial9\ProjectFiles\Tutorial9.cbp           >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial10\ProjectFiles\Tutorial10.cbp         >>"..\output\CodeBlocks.log"
codeblocks.exe --rebuild Tutorial11\ProjectFiles\Tutorial11.cbp         >>"..\output\CodeBlocks.log"

mkdir "..\output\MinGW\Tutorials"
mkdir "..\output\MinGW\Tutorials\Debug"

ECHO "Copying Debug Tutorials" >>"..\output\CodeBlocks.log"
copy Tutorial1\ProjectFiles\GNU\Debug\Tutorial1.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial2\ProjectFiles\GNU\Debug\Tutorial2.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial3\ProjectFiles\GNU\Debug\Tutorial3.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial4\ProjectFiles\GNU\Debug\Tutorial4.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial5\ProjectFiles\GNU\Debug\Tutorial5.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial6\ProjectFiles\GNU\Debug\Tutorial6.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial7\ProjectFiles\GNU\Debug\Tutorial7.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial8\ProjectFiles\GNU\Debug\Tutorial8.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial9\ProjectFiles\GNU\Debug\Tutorial9.exe         "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial10\ProjectFiles\GNU\Debug\Tutorial10.exe       "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"
copy Tutorial11\ProjectFiles\GNU\Debug\Tutorial11.exe       "..\output\MinGW\Tutorials\Debug"    >>"..\output\CodeBlocks.log"

mkdir "..\output\MinGW\Tutorials\Release"

ECHO "Copying Release Tutorials" >>"..\output\CodeBlocks.log"
copy Tutorial1\ProjectFiles\GNU\Release\Tutorial1.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial2\ProjectFiles\GNU\Release\Tutorial2.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial3\ProjectFiles\GNU\Release\Tutorial3.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial4\ProjectFiles\GNU\Release\Tutorial4.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial5\ProjectFiles\GNU\Release\Tutorial5.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial6\ProjectFiles\GNU\Release\Tutorial6.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial7\ProjectFiles\GNU\Release\Tutorial7.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial8\ProjectFiles\GNU\Release\Tutorial8.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial9\ProjectFiles\GNU\Release\Tutorial9.exe       "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial10\ProjectFiles\GNU\Release\Tutorial10.exe     "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"
copy Tutorial11\ProjectFiles\GNU\Release\Tutorial11.exe     "..\output\MinGW\Tutorials\Release"    >>"..\output\CodeBlocks.log"

REM: Pop the directory change off the stack
popd

