@echo off
REM: A batch program to rebuild the Win32++ samples using C++ Builder 11 CE.
REM: The contents of the log file is erased 

REM: Set the paths and environment variables
call "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"

::Cleanup
call CleanSamples
call CleanTutorials

REM: Change the directory to the Samples parent
pushd ..\Samples
if exist "..\output\Embarcadero\Debug" rmdir /s /q "..\output\Embarcadero\Debug"
if exist "..\output\Embarcadero\Release" rmdir /s /q "..\output\Embarcadero\Release"
if exist "..\output\Embarcadero\Tutorials" rmdir /s /q "..\output\Embarcadero\Tutorials"

@echo on

::Compile code
msbuild Animation\ProjectFiles\Animation.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 > "..\output\Embarcadero.log"
msbuild Animation\ProjectFiles\Animation.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild Browser\ProjectFiles\Browser.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Browser\ProjectFiles\Browser.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild CommonDialogs\ProjectFiles\CommonDialogs.cbproj /t:build /p:Config=Debug /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild CommonDialogs\ProjectFiles\CommonDialogs.cbproj /t:build /p:Config=Release /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild Console\ProjectFiles\Console.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Console\ProjectFiles\Console.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild ContextHelp\ProjectFiles\ContextHelp.cbproj /t:build /p:Config=Debug /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild ContextHelp\ProjectFiles\ContextHelp.cbproj /t:build /p:Config=Release /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild CustomControl\ProjectFiles\CustomControl.cbproj /t:build /p:Config=Debug /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild CustomControl\ProjectFiles\CustomControl.cbproj /t:build /p:Config=Release /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild CustomPrintDlg\ProjectFiles\CustomPrintDlg.cbproj /t:build /p:Config=Debug /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild CustomPrintDlg\ProjectFiles\CustomPrintDlg.cbproj /t:build /p:Config=Release /p:Platform=Win64x     >>"..\output\Embarcadero.log"
msbuild DateTime\ProjectFiles\DateTime.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild DateTime\ProjectFiles\DateTime.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild DDXDemo\ProjectFiles\DDXDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild DDXDemo\ProjectFiles\DDXDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild Dialog\ProjectFiles\Dialog.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                       >>"..\output\Embarcadero.log"
msbuild Dialog\ProjectFiles\Dialog.cbproj /t:build /p:Config=Release /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild DialogBars\ProjectFiles\DialogBars.cbproj /t:build /p:Config=Debug /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild DialogBars\ProjectFiles\DialogBars.cbproj /t:build /p:Config=Release /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild DialogDemo\ProjectFiles\DialogDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild DialogDemo\ProjectFiles\DialogDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild DialogResizing\ProjectFiles\DialogResizing.cbproj /t:build /p:Config=Debug /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild DialogResizing\ProjectFiles\DialogResizing.cbproj /t:build /p:Config=Release /p:Platform=Win64x     >>"..\output\Embarcadero.log"
msbuild DialogTab\ProjectFiles\DialogTab.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild DialogTab\ProjectFiles\DialogTab.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild DialogTemplate\ProjectFiles\DialogTemplate.cbproj /t:build /p:Config=Debug /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild DialogTemplate\ProjectFiles\DialogTemplate.cbproj /t:build /p:Config=Release /p:Platform=Win64x     >>"..\output\Embarcadero.log"
msbuild Dock\ProjectFiles\Dock.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                           >>"..\output\Embarcadero.log"
msbuild Dock\ProjectFiles\Dock.cbproj /t:build /p:Config=Release /p:Platform=Win64x                         >>"..\output\Embarcadero.log"
msbuild DockContainer\ProjectFiles\DockContainer.cbproj /t:build /p:Config=Debug /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild DockContainer\ProjectFiles\DockContainer.cbproj /t:build /p:Config=Release /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild DockTabbedMDI\ProjectFiles\DockTabbedMDI.cbproj /t:build /p:Config=Debug /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild DockTabbedMDI\ProjectFiles\DockTabbedMDI.cbproj /t:build /p:Config=Release /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild DoubleBuffer\ProjectFiles\DoubleBuffer.cbproj /t:build /p:Config=Debug /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild DoubleBuffer\ProjectFiles\DoubleBuffer.cbproj /t:build /p:Config=Release /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild Explorer\ProjectFiles\Explorer.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild Explorer\ProjectFiles\Explorer.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild FastGDI\ProjectFiles\FastGDI.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild FastGDI\ProjectFiles\FastGDI.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild FilePrintPreview\ProjectFiles\FilePrintPreview.cbproj /t:build /p:Config=Debug /p:Platform=Win64x   >>"..\output\Embarcadero.log"
msbuild FilePrintPreview\ProjectFiles\FilePrintPreview.cbproj /t:build /p:Config=Release /p:Platform=Win64x >>"..\output\Embarcadero.log"
msbuild FormDocView\ProjectFiles\FormDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                >>"..\output\Embarcadero.log"
msbuild FormDocView\ProjectFiles\FormDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x              >>"..\output\Embarcadero.log"
msbuild Frame\ProjectFiles\Frame.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                         >>"..\output\Embarcadero.log"
msbuild Frame\ProjectFiles\Frame.cbproj /t:build /p:Config=Release /p:Platform=Win64x                       >>"..\output\Embarcadero.log"
msbuild FrameEx\ProjectFiles\FrameEx.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild FrameEx\ProjectFiles\FrameEx.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild GDIPlus\ProjectFiles\GDIPlus.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild GDIPlus\ProjectFiles\GDIPlus.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild INIFrame\ProjectFiles\INIFrame.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild INIFrame\ProjectFiles\INIFrame.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild ListView\ProjectFiles\ListView.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild ListView\ProjectFiles\ListView.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild MDIDockFrame\ProjectFiles\MDIDockFrame.cbproj /t:build /p:Config=Debug /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild MDIDockFrame\ProjectFiles\MDIDockFrame.cbproj /t:build /p:Config=Release /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild MDIFrame\ProjectFiles\MDIFrame.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild MDIFrame\ProjectFiles\MDIFrame.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild MDIFrameDemo\ProjectFiles\MDIFrameDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild MDIFrameDemo\ProjectFiles\MDIFrameDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild MDIFrameSplitter\ProjectFiles\MDIFrameSplitter.cbproj /t:build /p:Config=Debug /p:Platform=Win64x   >>"..\output\Embarcadero.log"
msbuild MDIFrameSplitter\ProjectFiles\MDIFrameSplitter.cbproj /t:build /p:Config=Release /p:Platform=Win64x >>"..\output\Embarcadero.log"
msbuild MetaFile\ProjectFiles\MetaFile.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild MetaFile\ProjectFiles\MetaFile.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild MovieShow\ProjectFiles\MovieShow.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild MovieShow\ProjectFiles\MovieShow.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild NetClient\ProjectFiles\NetClient.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild NetClient\ProjectFiles\NetClient.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild NetServer\ProjectFiles\NetServer.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild NetServer\ProjectFiles\NetServer.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild Notepad\ProjectFiles\Notepad.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Notepad\ProjectFiles\Notepad.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild Performance\ProjectFiles\Performance.cbproj /t:build /p:Config=Debug /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild Performance\ProjectFiles\Performance.cbproj /t:build /p:Config=Release /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild Picture\ProjectFiles\Picture.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Picture\ProjectFiles\Picture.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild PropertySheet\ProjectFiles\PropertySheet.cbproj /t:build /p:Config=Debug /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild PropertySheet\ProjectFiles\PropertySheet.cbproj /t:build /p:Config=Release /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild ReBarDemo\ProjectFiles\ReBarDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild ReBarDemo\ProjectFiles\ReBarDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild RoundWindow\ProjectFiles\RoundWindow.cbproj /t:build /p:Config=Debug /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild RoundWindow\ProjectFiles\RoundWindow.cbproj /t:build /p:Config=Release /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild ScintillaDemo\ProjectFiles\ScintillaDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x         >>"..\output\Embarcadero.log"
msbuild ScintillaDemo\ProjectFiles\ScintillaDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild Scribble\ProjectFiles\Scribble.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild Scribble\ProjectFiles\Scribble.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild Simple\ProjectFiles\Simple.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                       >>"..\output\Embarcadero.log"
msbuild Simple\ProjectFiles\Simple.cbproj /t:build /p:Config=Release /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Splitter\ProjectFiles\Splitter.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild Splitter\ProjectFiles\Splitter.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild StatusBar\ProjectFiles\StatusBar.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild StatusBar\ProjectFiles\StatusBar.cbproj /t:build /p:Config=Release /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild TabDemo\ProjectFiles\TabDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild TabDemo\ProjectFiles\TabDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild TaskDialog\ProjectFiles\TaskDialog.cbproj /t:build /p:Config=Debug /p:Platform=Win64x               >>"..\output\Embarcadero.log"
msbuild TaskDialog\ProjectFiles\TaskDialog.cbproj /t:build /p:Config=Release /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild TextFileReader\ProjectFiles\TextFileReader.cbproj /t:build /p:Config=Debug /p:Platform=Win64x       >>"..\output\Embarcadero.log"
msbuild TextFileReader\ProjectFiles\TextFileReader.cbproj /t:build /p:Config=Release /p:Platform=Win64x     >>"..\output\Embarcadero.log"
msbuild Themes\ProjectFiles\Themes.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                       >>"..\output\Embarcadero.log"
msbuild Themes\ProjectFiles\Themes.cbproj /t:build /p:Config=Release /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Threads\ProjectFiles\Threads.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild Threads\ProjectFiles\Threads.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild TimeDemo\ProjectFiles\TimeDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild TimeDemo\ProjectFiles\TimeDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild ToolBarDemo\ProjectFiles\ToolBarDemo.cbproj /t:build /p:Config=Debug /p:Platform=Win64x             >>"..\output\Embarcadero.log"
msbuild ToolBarDemo\ProjectFiles\ToolBarDemo.cbproj /t:build /p:Config=Release /p:Platform=Win64x           >>"..\output\Embarcadero.log"
msbuild ToolTips\ProjectFiles\ToolTips.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                   >>"..\output\Embarcadero.log"
msbuild ToolTips\ProjectFiles\ToolTips.cbproj /t:build /p:Config=Release /p:Platform=Win64x                 >>"..\output\Embarcadero.log"
msbuild Tray\ProjectFiles\Tray.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                           >>"..\output\Embarcadero.log"
msbuild Tray\ProjectFiles\Tray.cbproj /t:build /p:Config=Release /p:Platform=Win64x                         >>"..\output\Embarcadero.log"
msbuild WinPlot\ProjectFiles\WinPlot.cbproj /t:build /p:Config=Debug /p:Platform=Win64x                     >>"..\output\Embarcadero.log"
msbuild WinPlot\ProjectFiles\WinPlot.cbproj /t:build /p:Config=Release /p:Platform=Win64x                   >>"..\output\Embarcadero.log"

mkdir "..\output\Embarcadero"
mkdir "..\output\Embarcadero\Debug"

ECHO "Copying Debug Samples" >>"..\output\Embarcadero.log"
copy Animation\ProjectFiles\Embarcadero\Win64x\Debug\Animation.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Browser\ProjectFiles\Embarcadero\Win64x\Debug\Browser.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy CommonDialogs\ProjectFiles\Embarcadero\Win64x\Debug\CommonDialogs.exe       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Console\ProjectFiles\Embarcadero\Win64x\Debug\Console.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ContextHelp\ProjectFiles\Embarcadero\Win64x\Debug\ContextHelp.exe           "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ContextHelp\Setup\ContextHelp.chm                                           "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy CustomControl\ProjectFiles\Embarcadero\Win64x\Debug\CustomControl.exe       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy CustomPrintDlg\ProjectFiles\Embarcadero\Win64x\Debug\CustomPrintDlg.exe     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DateTime\ProjectFiles\Embarcadero\Win64x\Debug\DateTime.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DDXDemo\ProjectFiles\Embarcadero\Win64x\Debug\DDXDemo.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Dialog\ProjectFiles\Embarcadero\Win64x\Debug\Dialog.exe                     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DialogBars\ProjectFiles\Embarcadero\Win64x\Debug\DialogBars.exe             "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DialogDemo\ProjectFiles\Embarcadero\Win64x\Debug\DialogDemo.exe             "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DialogResizing\ProjectFiles\Embarcadero\Win64x\Debug\DialogResizing.exe     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DialogTab\ProjectFiles\Embarcadero\Win64x\Debug\DialogTab.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DialogTemplate\ProjectFiles\Embarcadero\Win64x\Debug\DialogTemplate.exe     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Dock\ProjectFiles\Embarcadero\Win64x\Debug\Dock.exe                         "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DockContainer\ProjectFiles\Embarcadero\Win64x\Debug\DockContainer.exe       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DockTabbedMDI\ProjectFiles\Embarcadero\Win64x\Debug\DockTabbedMDI.exe       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy DoubleBuffer\ProjectFiles\Embarcadero\Win64x\Debug\DoubleBuffer.exe         "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Explorer\ProjectFiles\Embarcadero\Win64x\Debug\Explorer.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy FastGDI\ProjectFiles\Embarcadero\Win64x\Debug\FastGDI.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy FilePrintPreview\ProjectFiles\Embarcadero\Win64x\Debug\FilePrintPreview.exe "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy FormDocView\ProjectFiles\Embarcadero\Win64x\Debug\FormDemo.exe              "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Frame\ProjectFiles\Embarcadero\Win64x\Debug\Frame.exe                       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy FrameEx\ProjectFiles\Embarcadero\Win64x\Debug\FrameEx.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy GDIPlus\ProjectFiles\Embarcadero\Win64x\Debug\GDIPlus.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy INIFrame\ProjectFiles\Embarcadero\Win64x\Debug\INIFrame.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ListView\ProjectFiles\Embarcadero\Win64x\Debug\ListView.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MDIDockFrame\ProjectFiles\Embarcadero\Win64x\Debug\MDIDockFrame.exe         "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MDIFrame\ProjectFiles\Embarcadero\Win64x\Debug\MDIFrame.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MDIFrameDemo\ProjectFiles\Embarcadero\Win64x\Debug\MDIFrameDemo.exe         "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MDIFrameSplitter\ProjectFiles\Embarcadero\Win64x\Debug\MDIFrameSplitter.exe "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MetaFile\ProjectFiles\Embarcadero\Win64x\Debug\MetaFile.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MovieShow\ProjectFiles\Embarcadero\Win64x\Debug\MovieShow.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy MovieShow\install\files\MediaInfo.dll                                       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy NetClient\ProjectFiles\Embarcadero\Win64x\Debug\NetClient.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy NetServer\ProjectFiles\Embarcadero\Win64x\Debug\NetServer.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Notepad\ProjectFiles\Embarcadero\Win64x\Debug\Notepad.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Performance\ProjectFiles\Embarcadero\Win64x\Debug\Performance.exe           "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Picture\ProjectFiles\Embarcadero\Win64x\Debug\Picture.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ReBarDemo\ProjectFiles\Embarcadero\Win64x\Debug\ReBarDemo.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy RoundWindow\ProjectFiles\Embarcadero\Win64x\Debug\RoundWindow.exe           "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ScintillaDemo\ProjectFiles\Embarcadero\Win64x\Debug\ScintillaDemo.exe       "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ScintillaDemo\DLLs\x64\Scintilla.dll                                        "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Scribble\ProjectFiles\Embarcadero\Win64x\Debug\Scribble.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Simple\ProjectFiles\Embarcadero\Win64x\Debug\Simple.exe                     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Splitter\ProjectFiles\Embarcadero\Win64x\Debug\Splitter.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy StatusBar\ProjectFiles\Embarcadero\Win64x\Debug\StatusBar.exe               "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy TabDemo\ProjectFiles\Embarcadero\Win64x\Debug\TabDemo.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy TaskDialog\ProjectFiles\Embarcadero\Win64x\Debug\TaskDialog.exe             "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy TextFileReader\ProjectFiles\Embarcadero\Win64x\Debug\TextFileReader.exe     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Themes\ProjectFiles\Embarcadero\Win64x\Debug\Themes.exe                     "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Threads\ProjectFiles\Embarcadero\Win64x\Debug\Threads.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy TimeDemo\ProjectFiles\Embarcadero\Win64x\Debug\TimeDemo.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ToolBarDemo\ProjectFiles\Embarcadero\Win64x\Debug\ToolBarDemo.exe           "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy ToolTips\ProjectFiles\Embarcadero\Win64x\Debug\ToolTips.exe                 "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy Tray\ProjectFiles\Embarcadero\Win64x\Debug\Tray.exe                         "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"
copy WinPlot\ProjectFiles\Embarcadero\Win64x\Debug\WinPlot.exe                   "..\output\Embarcadero\Debug"    >>"..\output\Embarcadero.log"

mkdir "..\output\Embarcadero\Release"

ECHO "Copying Release Samples" >>"..\output\Embarcadero.log"
copy Animation\ProjectFiles\Embarcadero\Win64x\Release\Animation.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Browser\ProjectFiles\Embarcadero\Win64x\Release\Browser.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy CommonDialogs\ProjectFiles\Embarcadero\Win64x\Release\CommonDialogs.exe       "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Console\ProjectFiles\Embarcadero\Win64x\Release\Console.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ContextHelp\ProjectFiles\Embarcadero\Win64x\Release\ContextHelp.exe           "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy CustomControl\ProjectFiles\Embarcadero\Win64x\Release\CustomControl.exe       "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ContextHelp\Setup\ContextHelp.chm                                             "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy CustomPrintDlg\ProjectFiles\Embarcadero\Win64x\Release\CustomPrintDlg.exe     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DateTime\ProjectFiles\Embarcadero\Win64x\Release\DateTime.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DDXDemo\ProjectFiles\Embarcadero\Win64x\Release\DDXDemo.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Dialog\ProjectFiles\Embarcadero\Win64x\Release\Dialog.exe                     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DialogBars\ProjectFiles\Embarcadero\Win64x\Release\DialogBars.exe             "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DialogDemo\ProjectFiles\Embarcadero\Win64x\Release\DialogDemo.exe             "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DialogResizing\ProjectFiles\Embarcadero\Win64x\Release\DialogResizing.exe     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DialogTab\ProjectFiles\Embarcadero\Win64x\Release\DialogTab.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DialogTemplate\ProjectFiles\Embarcadero\Win64x\Release\DialogTemplate.exe     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Dock\ProjectFiles\Embarcadero\Win64x\Release\Dock.exe                         "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DockContainer\ProjectFiles\Embarcadero\Win64x\Release\DockContainer.exe       "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DockTabbedMDI\ProjectFiles\Embarcadero\Win64x\Release\DockTabbedMDI.exe       "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy DoubleBuffer\ProjectFiles\Embarcadero\Win64x\Release\DoubleBuffer.exe         "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Explorer\ProjectFiles\Embarcadero\Win64x\Release\Explorer.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy FastGDI\ProjectFiles\Embarcadero\Win64x\Release\FastGDI.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy FilePrintPreview\ProjectFiles\Embarcadero\Win64x\Release\FilePrintPreview.exe "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy FormDocView\ProjectFiles\Embarcadero\Win64x\Release\FormDemo.exe              "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Frame\ProjectFiles\Embarcadero\Win64x\Release\Frame.exe                       "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy FrameEx\ProjectFiles\Embarcadero\Win64x\Release\FrameEx.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy GDIPlus\ProjectFiles\Embarcadero\Win64x\Release\GDIPlus.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy INIFrame\ProjectFiles\Embarcadero\Win64x\Release\INIFrame.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ListView\ProjectFiles\Embarcadero\Win64x\Release\ListView.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MDIDockFrame\ProjectFiles\Embarcadero\Win64x\Release\MDIDockFrame.exe         "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MDIFrame\ProjectFiles\Embarcadero\Win64x\Release\MDIFrame.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MDIFrameDemo\ProjectFiles\Embarcadero\Win64x\Release\MDIFrameDemo.exe         "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MDIFrameSplitter\ProjectFiles\Embarcadero\Win64x\Release\MDIFrameSplitter.exe "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MetaFile\ProjectFiles\Embarcadero\Win64x\Release\MetaFile.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MovieShow\ProjectFiles\Embarcadero\Win64x\Release\MovieShow.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy MovieShow\install\files\MediaInfo.dll                                         "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy NetClient\ProjectFiles\Embarcadero\Win64x\Release\NetClient.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy NetServer\ProjectFiles\Embarcadero\Win64x\Release\NetServer.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Notepad\ProjectFiles\Embarcadero\Win64x\Release\Notepad.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Performance\ProjectFiles\Embarcadero\Win64x\Release\Performance.exe           "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Picture\ProjectFiles\Embarcadero\Win64x\Release\Picture.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ReBarDemo\ProjectFiles\Embarcadero\Win64x\Release\ReBarDemo.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy RoundWindow\ProjectFiles\Embarcadero\Win64x\Release\RoundWindow.exe           "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ScintillaDemo\ProjectFiles\Embarcadero\Win64x\Release\ScintillaDemo.exe       "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ScintillaDemo\DLLs\x64\Scintilla.dll                                          "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Scribble\ProjectFiles\Embarcadero\Win64x\Release\Scribble.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Simple\ProjectFiles\Embarcadero\Win64x\Release\Simple.exe                     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Splitter\ProjectFiles\Embarcadero\Win64x\Release\Splitter.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy StatusBar\ProjectFiles\Embarcadero\Win64x\Release\StatusBar.exe               "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy TabDemo\ProjectFiles\Embarcadero\Win64x\Release\TabDemo.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy TaskDialog\ProjectFiles\Embarcadero\Win64x\Release\TaskDialog.exe             "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy TextFileReader\ProjectFiles\Embarcadero\Win64x\Release\TextFileReader.exe     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Themes\ProjectFiles\Embarcadero\Win64x\Release\Themes.exe                     "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Threads\ProjectFiles\Embarcadero\Win64x\Release\Threads.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy TimeDemo\ProjectFiles\Embarcadero\Win64x\Release\TimeDemo.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ToolBarDemo\ProjectFiles\Embarcadero\Win64x\Release\ToolBarDemo.exe           "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy ToolTips\ProjectFiles\Embarcadero\Win64x\Release\ToolTips.exe                 "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy Tray\ProjectFiles\Embarcadero\Win64x\Release\Tray.exe                         "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"
copy WinPlot\ProjectFiles\Embarcadero\Win64x\Release\WinPlot.exe                   "..\output\Embarcadero\Release"    >>"..\output\Embarcadero.log"

REM: Pop the directory change off the stack
popd


