REM: A batch program to rebuild the Win32++ samples using VS2026 Community.
REM: The contents of the log file is erased 

REM: Set the paths and environment variables
call "C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvarsall.bat" x64


::Cleanup
call CleanSamples
call CleanTutorials

REM: Change the directory to the Samples parent
pushd ..\Samples
if exist "..\output\VS2026\Debug" rmdir /s /q "..\output\VS2026\Debug"
if exist "..\output\VS2026\Release" rmdir /s /q "..\output\VS2026\Release"
if exist "..\output\VS2026\Tutorials" rmdir /s /q "..\output\VS2026\Tutorials"
if not exist "..\output" mkdir "..\output"

@echo on

::Compile code
MSBuild Animation\ProjectFiles\Animation_2026.slnx /p:Configuration=Debug /p:Platform=x64                 > "..\output\VS2026.log"
MSBuild Animation\ProjectFiles\Animation_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild Browser\ProjectFiles\Browser_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild Browser\ProjectFiles\Browser_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild BrowserATL\ProjectFiles\BrowserATL_2026.slnx /p:Configuration=Debug /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild BrowserATL\ProjectFiles\BrowserATL_2026.slnx /p:Configuration=Release /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild CommonDialogs\ProjectFiles\CommonDialogs_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild CommonDialogs\ProjectFiles\CommonDialogs_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild Console\ProjectFiles\Console_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild Console\ProjectFiles\Console_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild ContextHelp\ProjectFiles\ContextHelp_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild ContextHelp\ProjectFiles\ContextHelp_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild CustomControl\ProjectFiles\CustomControl_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild CustomControl\ProjectFiles\CustomControl_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild CustomPrintDlg\ProjectFiles\CustomPrintDlg_2026.slnx /p:Configuration=Debug /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild CustomPrintDlg\ProjectFiles\CustomPrintDlg_2026.slnx /p:Configuration=Release /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild DarkModeFrame\ProjectFiles\DarkModeFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild DarkModeFrame\ProjectFiles\DarkModeFrame_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild DateTime\ProjectFiles\DateTime_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild DateTime\ProjectFiles\DateTime_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild DDXDemo\ProjectFiles\DDXDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild DDXDemo\ProjectFiles\DDXDemo_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Dialog\ProjectFiles\Dialog_2026.slnx /p:Configuration=Debug /p:Platform=x64                       >>"..\output\VS2026.log"
MSBuild Dialog\ProjectFiles\Dialog_2026.slnx /p:Configuration=Release /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild DialogBars\ProjectFiles\DialogBars_2026.slnx /p:Configuration=Debug /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild DialogBars\ProjectFiles\DialogBars_2026.slnx /p:Configuration=Release /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild DialogDemo\ProjectFiles\DialogDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild DialogDemo\ProjectFiles\DialogDemo_2026.slnx /p:Configuration=Release /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild DialogResizing\ProjectFiles\DialogResizing_2026.slnx /p:Configuration=Debug /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild DialogResizing\ProjectFiles\DialogResizing_2026.slnx /p:Configuration=Release /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild DialogTab\ProjectFiles\DialogTab_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild DialogTab\ProjectFiles\DialogTab_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild DialogTemplate\ProjectFiles\DialogTemplate_2026.slnx /p:Configuration=Debug /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild DialogTemplate\ProjectFiles\DialogTemplate_2026.slnx /p:Configuration=Release /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild Direct2D\ProjectFiles\Direct2D_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Direct2D\ProjectFiles\Direct2D_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild DirectX9\ProjectFiles\DirectX9_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild DirectX9\ProjectFiles\DirectX9_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild DirectX11\ProjectFiles\DirectX11_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild DirectX11\ProjectFiles\DirectX11_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild Dock\ProjectFiles\Dock_2026.slnx /p:Configuration=Debug /p:Platform=x64                           >>"..\output\VS2026.log"
MSBuild Dock\ProjectFiles\Dock_2026.slnx /p:Configuration=Release /p:Platform=x64                         >>"..\output\VS2026.log"
MSBuild DockContainer\ProjectFiles\DockContainer_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild DockContainer\ProjectFiles\DockContainer_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild DockTabbedMDI\ProjectFiles\DockTabbedMDI_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild DockTabbedMDI\ProjectFiles\DockTabbedMDI_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild DoubleBuffer\ProjectFiles\DoubleBuffer_2026.slnx /p:Configuration=Debug /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild DoubleBuffer\ProjectFiles\DoubleBuffer_2026.slnx /p:Configuration=Release /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild EdgeBrowser\ProjectFiles\EdgeBrowser_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild EdgeBrowser\ProjectFiles\EdgeBrowser_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild EdgeBrowserEx\ProjectFiles\EdgeBrowserEx_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild EdgeBrowserEx\ProjectFiles\EdgeBrowserEx_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild Explorer\ProjectFiles\Explorer_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Explorer\ProjectFiles\Explorer_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild FastGDI\ProjectFiles\FastGDI_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild FastGDI\ProjectFiles\FastGDI_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild FilePrintPreview\ProjectFiles\FilePrintPreview_2026.slnx /p:Configuration=Debug /p:Platform=x64   >>"..\output\VS2026.log"
MSBuild FilePrintPreview\ProjectFiles\FilePrintPreview_2026.slnx /p:Configuration=Release /p:Platform=x64 >>"..\output\VS2026.log"
MSBuild FormDocView\ProjectFiles\FormDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64                >>"..\output\VS2026.log"
MSBuild FormDocView\ProjectFiles\FormDemo_2026.slnx /p:Configuration=Release /p:Platform=x64              >>"..\output\VS2026.log"
MSBuild Frame\ProjectFiles\Frame_2026.slnx /p:Configuration=Debug /p:Platform=x64                         >>"..\output\VS2026.log"
MSBuild Frame\ProjectFiles\Frame_2026.slnx /p:Configuration=Release /p:Platform=x64                       >>"..\output\VS2026.log"
MSBuild FrameEx\ProjectFiles\FrameEx_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild FrameEx\ProjectFiles\FrameEx_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild IFileDialog\ProjectFiles\IFileDialog_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild IFileDialog\ProjectFiles\IFileDialog_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild INIFrame\ProjectFiles\INIFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild INIFrame\ProjectFiles\INIFrame_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild GDIPlus\ProjectFiles\GDIPlus_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild GDIPlus\ProjectFiles\GDIPlus_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild ListView\ProjectFiles\ListView_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild ListView\ProjectFiles\ListView_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild MakeDLL\ProjectFiles\MakeDLL_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild MakeDLL\ProjectFiles\MakeDLL_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild MDIDockFrame\ProjectFiles\MDIDockFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild MDIDockFrame\ProjectFiles\MDIDockFrame_2026.slnx /p:Configuration=Release /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild MDIFrame\ProjectFiles\MDIFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild MDIFrame\ProjectFiles\MDIFrame_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild MDIFrameDemo\ProjectFiles\MDIFrameDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild MDIFrameDemo\ProjectFiles\MDIFrameDemo_2026.slnx /p:Configuration=Release /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild MDIFrameSplitter\ProjectFiles\MDIFrameSplitter_2026.slnx /p:Configuration=Debug /p:Platform=x64   >>"..\output\VS2026.log"
MSBuild MDIFrameSplitter\ProjectFiles\MDIFrameSplitter_2026.slnx /p:Configuration=Release /p:Platform=x64 >>"..\output\VS2026.log"
MSBuild MetaFile\ProjectFiles\MetaFile_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild MetaFile\ProjectFiles\MetaFile_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild MovieShow\ProjectFiles\MovieShow_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild MovieShow\ProjectFiles\MovieShow_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild NetClient\ProjectFiles\NetClient_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild NetClient\ProjectFiles\NetClient_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild NetServer\ProjectFiles\NetServer_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild NetServer\ProjectFiles\NetServer_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild NotePad\ProjectFiles\Notepad_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild NotePad\ProjectFiles\Notepad_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Performance\ProjectFiles\Performance_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild Performance\ProjectFiles\Performance_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild Picture\ProjectFiles\Picture_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild Picture\ProjectFiles\Picture_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild PropertySheet\ProjectFiles\PropertySheet_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild PropertySheet\ProjectFiles\PropertySheet_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild ReBarDemo\ProjectFiles\ReBarDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild ReBarDemo\ProjectFiles\ReBarDemo_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild Ribbon\ProjectFiles\Ribbon_2026.slnx /p:Configuration=Debug /p:Platform=x64                       >>"..\output\VS2026.log"
MSBuild Ribbon\ProjectFiles\Ribbon_2026.slnx /p:Configuration=Release /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild RibbonDockFrame\ProjectFiles\RibbonDockFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild RibbonDockFrame\ProjectFiles\RibbonDockFrame_2026.slnx /p:Configuration=Release /p:Platform=x64   >>"..\output\VS2026.log"
MSBuild RibbonFrame\ProjectFiles\RibbonFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild RibbonFrame\ProjectFiles\RibbonFrame_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild RibbonMDIFrame\ProjectFiles\RibbonMDIFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild RibbonMDIFrame\ProjectFiles\RibbonMDIFrame_2026.slnx /p:Configuration=Release /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild RoundWindow\ProjectFiles\RoundWindow_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild RoundWindow\ProjectFiles\RoundWindow_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild ScintillaDemo\ProjectFiles\ScintillaDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild ScintillaDemo\ProjectFiles\ScintillaDemo_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild Scribble\ProjectFiles\Scribble_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Scribble\ProjectFiles\Scribble_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild Simple\ProjectFiles\Simple_2026.slnx /p:Configuration=Debug /p:Platform=x64                       >>"..\output\VS2026.log"
MSBuild Simple\ProjectFiles\Simple_2026.slnx /p:Configuration=Release /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild Splitter\ProjectFiles\Splitter_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Splitter\ProjectFiles\Splitter_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild StatusBar\ProjectFiles\StatusBar_2026.slnx /p:Configuration=Debug /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild StatusBar\ProjectFiles\StatusBar_2026.slnx /p:Configuration=Release /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild TabDemo\ProjectFiles\TabDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild TabDemo\ProjectFiles\TabDemo_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild TaskDialog\ProjectFiles\TaskDialog_2026.slnx /p:Configuration=Debug /p:Platform=x64               >>"..\output\VS2026.log"
MSBuild TaskDialog\ProjectFiles\TaskDialog_2026.slnx /p:Configuration=Release /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild TestDLL\ProjectFiles\TestDLL_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild TestDLL\ProjectFiles\TestDLL_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild TextFileReader\ProjectFiles\TextFileReader_2026.slnx /p:Configuration=Debug /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild TextFileReader\ProjectFiles\TextFileReader_2026.slnx /p:Configuration=Release /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild Themes\ProjectFiles\Themes_2026.slnx /p:Configuration=Debug /p:Platform=x64                       >>"..\output\VS2026.log"
MSBuild Themes\ProjectFiles\Themes_2026.slnx /p:Configuration=Release /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild Threads\ProjectFiles\Threads_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild Threads\ProjectFiles\Threads_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild TimeDemo\ProjectFiles\TimeDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild TimeDemo\ProjectFiles\TimeDemo_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild Titlebar\ProjectFiles\Titlebar_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild Titlebar\ProjectFiles\Titlebar_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild TitlebarFrame\ProjectFiles\TitlebarFrame_2026.slnx /p:Configuration=Debug /p:Platform=x64         >>"..\output\VS2026.log"
MSBuild TitlebarFrame\ProjectFiles\TitlebarFrame_2026.slnx /p:Configuration=Release /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild ToolBarBuilder\ProjectFiles\ToolBarBuilder_2026.slnx /p:Configuration=Debug /p:Platform=x64       >>"..\output\VS2026.log"
MSBuild ToolBarBuilder\ProjectFiles\ToolBarBuilder_2026.slnx /p:Configuration=Release /p:Platform=x64     >>"..\output\VS2026.log"
MSBuild ToolBarDemo\ProjectFiles\ToolBarDemo_2026.slnx /p:Configuration=Debug /p:Platform=x64             >>"..\output\VS2026.log"
MSBuild ToolBarDemo\ProjectFiles\ToolBarDemo_2026.slnx /p:Configuration=Release /p:Platform=x64           >>"..\output\VS2026.log"
MSBuild ToolTips\ProjectFiles\ToolTips_2026.slnx /p:Configuration=Debug /p:Platform=x64                   >>"..\output\VS2026.log"
MSBuild ToolTips\ProjectFiles\ToolTips_2026.slnx /p:Configuration=Release /p:Platform=x64                 >>"..\output\VS2026.log"
MSBuild Tray\ProjectFiles\Tray_2026.slnx /p:Configuration=Debug /p:Platform=x64                           >>"..\output\VS2026.log"
MSBuild Tray\ProjectFiles\Tray_2026.slnx /p:Configuration=Release /p:Platform=x64                         >>"..\output\VS2026.log"
MSBuild WinPlot\ProjectFiles\WinPlot_2026.slnx /p:Configuration=Debug /p:Platform=x64                     >>"..\output\VS2026.log"
MSBuild WinPlot\ProjectFiles\WinPlot_2026.slnx /p:Configuration=Release /p:Platform=x64                   >>"..\output\VS2026.log"

mkdir "..\output\VS2026"
mkdir "..\output\VS2026\Debug"

ECHO "Copying Debug Samples" >>"..\output\VS2026.log"
copy Animation\ProjectFiles\x64\Debug\Animation.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Browser\ProjectFiles\x64\Debug\Browser.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy BrowserATL\ProjectFiles\x64\Debug\BrowserATL.exe             "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy CommonDialogs\ProjectFiles\x64\Debug\CommonDialogs.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Console\ProjectFiles\x64\Debug\Console.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ContextHelp\ProjectFiles\x64\Debug\ContextHelp.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ContextHelp\Setup\ContextHelp.chm                            "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy CustomControl\ProjectFiles\x64\Debug\CustomControl.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy CustomPrintDlg\ProjectFiles\x64\Debug\CustomPrintDlg.exe     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DarkModeFrame\ProjectFiles\x64\Debug\DarkFrame.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DateTime\ProjectFiles\x64\Debug\DateTime.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DDXDemo\ProjectFiles\x64\Debug\DDXDemo.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Dialog\ProjectFiles\x64\Debug\Dialog.exe                     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DialogBars\ProjectFiles\x64\Debug\DialogBars.exe             "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DialogDemo\ProjectFiles\x64\Debug\DialogDemo.exe             "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DialogResizing\ProjectFiles\x64\Debug\DialogResizing.exe     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DialogTab\ProjectFiles\x64\Debug\DialogTab.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DialogTemplate\ProjectFiles\x64\Debug\DialogTemplate.exe     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Direct2D\ProjectFiles\x64\Debug\Direct2D.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DirectX9\ProjectFiles\x64\Debug\DirectX9.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DirectX11\ProjectFiles\x64\Debug\DirectX11.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DirectX11\ProjectFiles\DirectX11.fx                          "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Dock\ProjectFiles\x64\Debug\Dock.exe                         "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DockContainer\ProjectFiles\x64\Debug\DockContainer.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DockTabbedMDI\ProjectFiles\x64\Debug\DockTabbedMDI.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy DoubleBuffer\ProjectFiles\x64\Debug\DoubleBuffer.exe         "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy EdgeBrowser\ProjectFiles\x64\Debug\EdgeBrowser.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy EdgeBrowser\ProjectFiles\x64\Debug\WebView2Loader.dll        "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy EdgeBrowserEx\ProjectFiles\x64\Debug\EdgeBrowserEx.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy EdgeBrowserEx\ProjectFiles\x64\Debug\WebView2Loader.dll      "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
xcopy "EdgeBrowserEx\src\wvbrowser_ui" "..\output\VS2026\Debug\wvbrowser_ui" /S /I /Y         >> "..\output\VS2026.log"
copy Explorer\ProjectFiles\x64\Debug\Explorer.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy FastGDI\ProjectFiles\x64\Debug\FastGDI.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy FilePrintPreview\ProjectFiles\x64\Debug\FilePrintPreview.exe "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy FormDocView\ProjectFiles\x64\Debug\FormDemo.exe              "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Frame\ProjectFiles\x64\Debug\Frame.exe                       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy FrameEx\ProjectFiles\x64\Debug\FrameEx.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy IFileDialog\ProjectFiles\x64\Debug\IFileDialog.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy INIFrame\ProjectFiles\x64\Debug\INIFrame.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy GDIPlus\ProjectFiles\x64\Debug\GDIPlus.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ListView\ProjectFiles\x64\Debug\ListView.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MakeDLL\ProjectFiles\x64\Debug\MyDLL.dll                     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MDIDockFrame\ProjectFiles\x64\Debug\MDIDockFrame.exe         "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MDIFrame\ProjectFiles\x64\Debug\MDIFrame.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MDIFrameDemo\ProjectFiles\x64\Debug\MDIFrameDemo.exe         "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MDIFrameSplitter\ProjectFiles\x64\Debug\MDIFrameSplitter.exe "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MetaFile\ProjectFiles\x64\Debug\MetaFile.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MovieShow\ProjectFiles\x64\Debug\MovieShow.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy MovieShow\DLLs\x64\MediaInfo.dll                             "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy NetClient\ProjectFiles\x64\Debug\NetClient.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy NetServer\ProjectFiles\x64\Debug\NetServer.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy NotePad\ProjectFiles\x64\Debug\Notepad.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Performance\ProjectFiles\x64\Debug\Performance.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Picture\ProjectFiles\x64\Debug\Picture.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy PropertySheet\ProjectFiles\x64\Debug\PropertySheet.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ReBarDemo\ProjectFiles\x64\Debug\ReBarDemo.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Ribbon\ProjectFiles\x64\Debug\Ribbon.exe                     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy RibbonDockFrame\ProjectFiles\x64\Debug\RibbonDockFrame.exe   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy RibbonFrame\ProjectFiles\x64\Debug\RibbonFrame.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy RibbonMDIFrame\ProjectFiles\x64\Debug\RibbonMDIFrame.exe     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy RoundWindow\ProjectFiles\x64\Debug\RoundWindow.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ScintillaDemo\ProjectFiles\x64\Debug\ScintillaDemo.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ScintillaDemo\DLLs\x64\Scintilla.dll                         "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Scribble\ProjectFiles\x64\Debug\Scribble.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Simple\ProjectFiles\x64\Debug\Simple.exe                     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Splitter\ProjectFiles\x64\Debug\Splitter.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy StatusBar\ProjectFiles\x64\Debug\StatusBar.exe               "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy TabDemo\ProjectFiles\x64\Debug\TabDemo.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy TaskDialog\ProjectFiles\x64\Debug\TaskDialog.exe             "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy TestDLL\ProjectFiles\x64\Debug\TestDLL.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy TextFileReader\ProjectFiles\x64\Debug\TextFileReader.exe     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Themes\ProjectFiles\x64\Debug\Themes.exe                     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Threads\ProjectFiles\x64\Debug\Threads.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy TimeDemo\ProjectFiles\x64\Debug\TimeDemo.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Titlebar\ProjectFiles\x64\Debug\Titlebar.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy TitlebarFrame\ProjectFiles\x64\Debug\TitlebarFrame.exe       "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ToolBarBuilder\ProjectFiles\x64\Debug\ToolBarBuilder.exe     "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ToolBarDemo\ProjectFiles\x64\Debug\ToolBarDemo.exe           "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy ToolTips\ProjectFiles\x64\Debug\ToolTips.exe                 "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy Tray\ProjectFiles\x64\Debug\Tray.exe                         "..\output\VS2026\Debug"    >>"..\output\VS2026.log"
copy WinPlot\ProjectFiles\x64\Debug\WinPlot.exe                   "..\output\VS2026\Debug"    >>"..\output\VS2026.log"

mkdir "..\output\VS2026\Release"

ECHO "Copying Release Samples" >>"..\output\VS2026.log"
copy Animation\ProjectFiles\x64\Release\Animation.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Browser\ProjectFiles\x64\Release\Browser.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy BrowserATL\ProjectFiles\x64\Release\BrowserATL.exe           "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy CommonDialogs\ProjectFiles\x64\Release\CommonDialogs.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Console\ProjectFiles\x64\Release\Console.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ContextHelp\ProjectFiles\x64\Release\ContextHelp.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ContextHelp\Setup\ContextHelp.chm                            "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy CustomControl\ProjectFiles\x64\Release\CustomControl.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy CustomPrintDlg\ProjectFiles\x64\Release\CustomPrintDlg.exe   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DarkModeFrame\ProjectFiles\x64\Release\DarkFrame.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DateTime\ProjectFiles\x64\Release\DateTime.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DDXDemo\ProjectFiles\x64\Release\DDXDemo.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Dialog\ProjectFiles\x64\Release\Dialog.exe                   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DialogBars\ProjectFiles\x64\Release\DialogBars.exe           "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DialogDemo\ProjectFiles\x64\Release\DialogDemo.exe           "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DialogResizing\ProjectFiles\x64\Release\DialogResizing.exe   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DialogTab\ProjectFiles\x64\Release\DialogTab.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DialogTemplate\ProjectFiles\x64\Release\DialogTemplate.exe   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Direct2D\ProjectFiles\x64\Release\Direct2D.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DirectX9\ProjectFiles\x64\Release\DirectX9.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DirectX11\ProjectFiles\x64\Release\DirectX11.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DirectX11\ProjectFiles\DirectX11.fx                          "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Dock\ProjectFiles\x64\Release\Dock.exe                       "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DockContainer\ProjectFiles\x64\Release\DockContainer.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DockTabbedMDI\ProjectFiles\x64\Release\DockTabbedMDI.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy DoubleBuffer\ProjectFiles\x64\Release\DoubleBuffer.exe       "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy EdgeBrowser\ProjectFiles\x64\Release\EdgeBrowser.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy EdgeBrowser\ProjectFiles\x64\Release\WebView2Loader.dll      "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy EdgeBrowserEx\ProjectFiles\x64\Release\EdgeBrowserEx.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy EdgeBrowserEx\ProjectFiles\x64\Release\WebView2Loader.dll    "..\output\VS2026\Release"    >>"..\output\VS2026.log"
xcopy "EdgeBrowserEx\src\wvbrowser_ui" "..\output\VS2026\Release\wvbrowser_ui" /S /I /Y         >>"..\output\VS2026.log"
copy Explorer\ProjectFiles\x64\Release\Explorer.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy FastGDI\ProjectFiles\x64\Release\FastGDI.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy FilePrintPreview\ProjectFiles\x64\Release\FilePrintPreview.exe "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy FormDocView\ProjectFiles\x64\Release\FormDemo.exe            "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Frame\ProjectFiles\x64\Release\Frame.exe                     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy FrameEx\ProjectFiles\x64\Release\FrameEx.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy IFileDialog\ProjectFiles\x64\Release\IFileDialog.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy INIFrame\ProjectFiles\x64\Release\INIFrame.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy GDIPlus\ProjectFiles\x64\Release\GDIPlus.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ListView\ProjectFiles\x64\Release\ListView.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MDIDockFrame\ProjectFiles\x64\Release\MDIDockFrame.exe       "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MDIFrame\ProjectFiles\x64\Release\MDIFrame.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MDIFrameDemo\ProjectFiles\x64\Release\MDIFrameDemo.exe       "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MDIFrameSplitter\ProjectFiles\x64\Release\MDIFrameSplitter.exe "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MakeDLL\ProjectFiles\x64\Release\MyDLL.dll                   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MetaFile\ProjectFiles\x64\Release\MetaFile.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MovieShow\ProjectFiles\x64\Release\MovieShow.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy MovieShow\DLLs\x64\MediaInfo.dll                             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy NetClient\ProjectFiles\x64\Release\NetClient.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy NetServer\ProjectFiles\x64\Release\NetServer.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy NotePad\ProjectFiles\x64\Release\Notepad.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Performance\ProjectFiles\x64\Release\Performance.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Picture\ProjectFiles\x64\Release\Picture.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy PropertySheet\ProjectFiles\x64\Release\PropertySheet.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ReBarDemo\ProjectFiles\x64\Release\ReBarDemo.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Ribbon\ProjectFiles\x64\Release\Ribbon.exe                   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy RibbonDockFrame\ProjectFiles\x64\Release\RibbonDockFrame.exe "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy RibbonFrame\ProjectFiles\x64\Release\RibbonFrame.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy RibbonMDIFrame\ProjectFiles\x64\Release\RibbonMDIFrame.exe   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy RoundWindow\ProjectFiles\x64\Release\RoundWindow.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ScintillaDemo\ProjectFiles\x64\Release\ScintillaDemo.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ScintillaDemo\DLLs\x64\Scintilla.dll                         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Scribble\ProjectFiles\x64\Release\Scribble.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Simple\ProjectFiles\x64\Release\Simple.exe                   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Splitter\ProjectFiles\x64\Release\Splitter.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy StatusBar\ProjectFiles\x64\Release\StatusBar.exe             "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy TabDemo\ProjectFiles\x64\Release\TabDemo.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy TaskDialog\ProjectFiles\x64\Release\TaskDialog.exe           "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy TestDLL\ProjectFiles\x64\Release\TestDLL.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy TextFileReader\ProjectFiles\x64\Release\TextFileReader.exe   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Themes\ProjectFiles\x64\Release\Themes.exe                   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Threads\ProjectFiles\x64\Release\Threads.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy TimeDemo\ProjectFiles\x64\Release\TimeDemo.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Titlebar\ProjectFiles\x64\Release\Titlebar.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy TitlebarFrame\ProjectFiles\x64\Release\TitlebarFrame.exe     "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ToolBarBuilder\ProjectFiles\x64\Release\ToolBarBuilder.exe   "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ToolBarDemo\ProjectFiles\x64\Release\ToolBarDemo.exe         "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy ToolTips\ProjectFiles\x64\Release\ToolTips.exe               "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy Tray\ProjectFiles\x64\Release\Tray.exe                       "..\output\VS2026\Release"    >>"..\output\VS2026.log"
copy WinPlot\ProjectFiles\x64\Release\WinPlot.exe                 "..\output\VS2026\Release"    >>"..\output\VS2026.log"


REM: Change the directory to the Tutorials parent
popd
pushd ..\Tutorials

REM: Compile Tutorials
ECHO "Compiling Tutorials" >>"..\output\VS2026.log"
::Compile code
MSBuild Tutorial1\ProjectFiles\Tutorial1_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial1\ProjectFiles\Tutorial1_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial2\ProjectFiles\Tutorial2_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial2\ProjectFiles\Tutorial2_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial3\ProjectFiles\Tutorial3_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial3\ProjectFiles\Tutorial3_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial4\ProjectFiles\Tutorial4_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial4\ProjectFiles\Tutorial4_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial5\ProjectFiles\Tutorial5_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial5\ProjectFiles\Tutorial5_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial6\ProjectFiles\Tutorial6_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial6\ProjectFiles\Tutorial6_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial7\ProjectFiles\Tutorial7_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial7\ProjectFiles\Tutorial7_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial8\ProjectFiles\Tutorial8_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial8\ProjectFiles\Tutorial8_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial9\ProjectFiles\Tutorial9_2026.slnx /p:Configuration=Debug /p:Platform=x64      >>"..\output\VS2026.log"
MSBuild Tutorial9\ProjectFiles\Tutorial9_2026.slnx /p:Configuration=Release /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial10\ProjectFiles\Tutorial10_2026.slnx /p:Configuration=Debug /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial10\ProjectFiles\Tutorial10_2026.slnx /p:Configuration=Release /p:Platform=x64  >>"..\output\VS2026.log"
MSBuild Tutorial11\ProjectFiles\Tutorial11_2026.slnx /p:Configuration=Debug /p:Platform=x64    >>"..\output\VS2026.log"
MSBuild Tutorial11\ProjectFiles\Tutorial11_2026.slnx /p:Configuration=Release /p:Platform=x64  >>"..\output\VS2026.log"

mkdir "..\output\VS2026\Tutorials"
mkdir "..\output\VS2026\Tutorials\Debug"

ECHO "Copying Debug Tutorials" >>"..\output\VS2026.log"
copy Tutorial1\ProjectFiles\x64\Debug\Tutorial1.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial2\ProjectFiles\x64\Debug\Tutorial2.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial3\ProjectFiles\x64\Debug\Tutorial3.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial4\ProjectFiles\x64\Debug\Tutorial4.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial5\ProjectFiles\x64\Debug\Tutorial5.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial6\ProjectFiles\x64\Debug\Tutorial6.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial7\ProjectFiles\x64\Debug\Tutorial7.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial8\ProjectFiles\x64\Debug\Tutorial8.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial9\ProjectFiles\x64\Debug\Tutorial9.exe         "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial10\ProjectFiles\x64\Debug\Tutorial10.exe       "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"
copy Tutorial11\ProjectFiles\x64\Debug\Tutorial11.exe       "..\output\VS2026\Tutorials\Debug"    >>"..\output\VS2026.log"

mkdir "..\output\VS2026\Tutorials\Release"

ECHO "Copying Release Tutorials" >>"..\output\VS2026.log"
copy Tutorial1\ProjectFiles\x64\Release\Tutorial1.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial2\ProjectFiles\x64\Release\Tutorial2.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial3\ProjectFiles\x64\Release\Tutorial3.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial4\ProjectFiles\x64\Release\Tutorial4.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial5\ProjectFiles\x64\Release\Tutorial5.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial6\ProjectFiles\x64\Release\Tutorial6.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial7\ProjectFiles\x64\Release\Tutorial7.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial8\ProjectFiles\x64\Release\Tutorial8.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial9\ProjectFiles\x64\Release\Tutorial9.exe       "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial10\ProjectFiles\x64\Release\Tutorial10.exe     "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"
copy Tutorial11\ProjectFiles\x64\Release\Tutorial11.exe     "..\output\VS2026\Tutorials\Release"    >>"..\output\VS2026.log"

REM: Pop the directory change off the stack
popd


